/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    metadata: Metadatum;
    themes: Theme;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    metadata: MetadataSelect<false> | MetadataSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('0' | '10' | '20' | '30' | '40' | '50') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedAt?: string | null;
  restaurant?: string | null;
  path: string;
  metadata?: (number | null) | Metadatum;
  layout: (
    | {
        logo: {
          image: number | Media;
          alt: string;
        };
        links?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        buttons?:
          | {
              text: string;
              url: string;
              style: 'fill' | 'outline';
              id?: string | null;
            }[]
          | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigation';
      }
    | {
        id: string | null;
        title: string;
        subtitle: string;
        description: string;
        backgroundImage: number | Media;
        buttonText: string;
        buttonLink: string;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'heroOne';
      }
    | {
        id: string | null;
        title: string;
        subtitle: string;
        description: string;
        buttonText: string;
        buttonLink: string;
        btn_variant?: ('fill' | 'outline') | null;
        image: number | Media;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'heroTwo';
      }
    | {
        id: string | null;
        title: string;
        description: string;
        images?:
          | {
              image: number | Media;
              category: string;
              id?: string | null;
            }[]
          | null;
        menu?:
          | {
              category: string;
              items?:
                | {
                    dish: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        buttonText: string;
        btn_style?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'singleLocation';
      }
    | {
        title: string;
        locations?:
          | {
              name: string;
              address: string;
              hours: string;
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        rewardsTitle?: string | null;
        rewardsDescription?: string | null;
        buttonText: string;
        btn_style?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'multipleLocations';
      }
    | {
        id: string | null;
        title: string;
        images?:
          | {
              image: number | Media;
              altText: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        id: string | null;
        title: string;
        image?: (number | null) | Media;
        franchiseSteps?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        investmentDetails?:
          | {
              title: string;
              amount: string;
              id?: string | null;
            }[]
          | null;
        buttonText: string;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'franchise';
      }
    | {
        id: string | null;
        title: string;
        items?:
          | {
              title: string;
              category?: string | null;
              specialTag?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        buttonText?: string | null;
        buttonLink?: string | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'menu';
      }
    | {
        id: string | null;
        title: string;
        description: string;
        fields?:
          | {
              label: string;
              name: string;
              type: 'text' | 'email' | 'textarea' | 'phone';
              required?: boolean | null;
              id?: string | null;
            }[]
          | null;
        buttonText: string;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        id: string | null;
        title: string;
        description: string;
        image?: (number | null) | Media;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'about';
      }
    | {
        id: string | null;
        logo?: (number | null) | Media;
        socialLinks?:
          | {
              platform?: ('facebook' | 'instagram' | 'youtube') | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        links?:
          | {
              label?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        copyright?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'footer';
      }
    | MediaBlock
    | FormBlock
    | {
        id: string | null;
        title: string;
        restaurants?:
          | {
              title: string;
              cuisine?: string | null;
              description?: string | null;
              image?: (number | null) | Media;
              buttonText: string;
              buttonLink: string;
              btn_style?: ('fill' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'restaurant';
      }
    | {
        id: string | null;
        title: string;
        locations?:
          | {
              image?: (number | null) | Media;
              name: string;
              address: string;
              buttonText: string;
              orderNowUrl: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'location';
      }
    | {
        id: string | null;
        title: string;
        locations?:
          | {
              image?: (number | null) | Media;
              name: string;
              address: string;
              orderNowUrl: string;
              id?: string | null;
            }[]
          | null;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'location_scroll';
      }
    | {
        id: string | null;
        title: string;
        categories?:
          | {
              categoryName: string;
              restaurants?:
                | {
                    title: string;
                    cuisine?: string | null;
                    description?: string | null;
                    image?: (number | null) | Media;
                    buttonText: string;
                    buttonLink: string;
                    variant?: ('fill' | 'outline') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'foodcourt';
      }
    | {
        id: string | null;
        title: string;
        chefs?:
          | {
              image?: (number | null) | Media;
              name: string;
              expertise: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'chef_details';
      }
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'about1';
      }
    | {
        id: string | null;
        title: string;
        testimonials?:
          | {
              name: string;
              designation?: string | null;
              testimonialText?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        id: string | null;
        title: string;
        chefs?:
          | {
              image?: (number | null) | Media;
              name: string;
              expertise: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'chef_sroll_details';
      }
    | {
        id: string | null;
        title: string;
        description?: string | null;
        email: string;
        phoneNumber: string;
        address: string;
        openHours?:
          | {
              day?: string | null;
              hours?: string | null;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'contact_us';
      }
    | {
        id: string | null;
        title: string;
        description: string;
        image?: (number | null) | Media;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'abouttwo';
      }
    | {
        title: string;
        items?:
          | {
              title: string;
              category: string;
              description?: string | null;
              image?: (number | null) | Media;
              price: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menu1';
      }
    | {
        id: string | null;
        title: string;
        description?: string | null;
        email: string;
        phoneNumber: string;
        address: string;
        openHours?:
          | {
              day?: string | null;
              hours?: string | null;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        fields?:
          | {
              label: string;
              name: string;
              type: 'text' | 'email' | 'textarea' | 'phone';
              required?: boolean | null;
              id?: string | null;
            }[]
          | null;
        buttonText?: string | null;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'contactus';
      }
    | {
        theme: 'black-theme' | 'white-theme' | 'orange-theme' | 'green-theme';
        logo: {
          image: number | Media;
          alt: string;
        };
        links?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        buttons?:
          | {
              text: string;
              url: string;
              style: 'fill' | 'outline';
              id?: string | null;
            }[]
          | null;
        menu?:
          | {
              text: string;
              url?: string | null;
              submenu?:
                | {
                    text: string;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigationDropDown';
      }
    | {
        id: string | null;
        imageShape: 'circular-image' | 'rectangle-image' | 'custom-image';
        title: string;
        subtitle: string;
        description: string;
        buttonText: string;
        buttonLink: string;
        btn_variant?: ('fill' | 'outline') | null;
        image: number | Media;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'heroThree';
      }
    | {
        captchaType: 'none' | 'googlerecaptcha' | 'cloudflareturnstile';
        storageType: 'database' | 'database-and-excel';
        workflow: string;
        title: string;
        description: string;
        form: number | Form;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact_two';
      }
    | {
        title: string;
        categories?:
          | {
              categoryName: string;
              items?:
                | {
                    title: string;
                    description?: string | null;
                    rating?: string | null;
                    price?: string | null;
                    image?: (number | null) | Media;
                    buttonText?: string | null;
                    buttonLink?: string | null;
                    btn_variant?: ('fill' | 'outline') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menutwo';
      }
    | {
        menu?:
          | {
              title: string;
              image?: (number | null) | Media;
              buttonLink: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menudisplay';
      }
    | {
        title: string;
        menu?:
          | {
              items?:
                | {
                    title: string;
                    description?: string | null;
                    rating?: string | null;
                    price?: string | null;
                    image?: (number | null) | Media;
                    buttonText?: string | null;
                    buttonLink?: string | null;
                    btn_variant?: ('fill' | 'outline') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuthree';
      }
    | {
        title: string;
        video?: (number | null) | Media;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        title: string;
        videoId: string;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoone';
      }
    | {
        title: string;
        videos: {
          videoId: string;
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videotwo';
      }
    | {
        title: string;
        videoId: string;
        description?: string | null;
        image?: (number | null) | Media;
        mediaPosition: 'left' | 'right';
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videothree';
      }
    | {
        layoutType: 'masonry' | 'carousel';
        title: string;
        images?:
          | {
              image: number | Media;
              altText: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'galleryone';
      }
    | {
        title: string;
        image?: (number | null) | Media;
        testimonials?:
          | {
              name: string;
              designation?: string | null;
              testimonialText?: string | null;
              Personimage?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonialtwo';
      }
    | {
        title: string;
        pages: {
          image?: (number | null) | Media;
          description: string;
          link: {
            page: number | Page;
            text: string;
          };
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'MainPage';
      }
    | {
        title: string;
        items?:
          | {
              title: string;
              description: string;
              iconName?: ('kitchen' | 'pantry' | 'location' | 'groups') | null;
              buttonText?: string | null;
              buttonLink?: string | null;
              /**
               * Provide a hex code (e.g. #8B2626, #F3EFE6, #2A5D34, #231F1D)
               */
              backgroundColor?: string | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menufour';
      }
    | {
        heading?: string | null;
        options: {
          name: string;
          icon?: (number | null) | Media;
          link: string;
          btn_variant?: ('fill' | 'outline') | null;
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceOptions';
      }
    | {
        title: string;
        restaurants?:
          | {
              title: string;
              cuisine?: string | null;
              description?: string | null;
              image?: (number | null) | Media;
              buttonText: string;
              buttonLink: string;
              variant?: ('fill' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'foodcourtone';
      }
    | {
        heading?: string | null;
        options: {
          name: string;
          icon?: (number | null) | Media;
          link: string;
          badge?: string | null;
          subtitle?: string | null;
          actionText?: string | null;
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceOptionsTwo';
      }
    | {
        heading?: string | null;
        description?: string | null;
        menuCategories: {
          name: string;
          image?: (number | null) | Media;
          link: string;
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menu-categories';
      }
    | {
        logo: {
          image: number | Media;
          alt: string;
        };
        links?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        buttons?:
          | {
              text: string;
              url: string;
              style: 'primary' | 'secondary';
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigationTwo';
      }
    | {
        colorScheme?: number | null;
        mode?: ('inherit' | 'light' | 'dark') | null;
        logo: {
          image: number | Media;
          alt: string;
        };
        links?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        buttons?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigationThree';
      }
    | {
        title?: string | null;
        videos?:
          | {
              platform?: ('instagram' | 'youtube') | null;
              videoUrl?: string | null;
              thumbnail?: (number | null) | Media;
              reelTitle?: string | null;
              views?: string | null;
              id?: string | null;
            }[]
          | null;
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'instagram';
      }
    | {
        heading?: string | null;
        subHeading?: string | null;
        buttonText?: string | null;
        videos?:
          | {
              uploadedVideo?: (number | null) | Media;
              videoUrl?: string | null;
              thumbnail?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroVideo';
      }
    | {
        heading?: string | null;
        options: {
          icon?: (number | null) | Media;
          name: string;
          link: string;
          description?: string | null;
          buttonText?: string | null;
          id?: string | null;
        }[];
        className?: string | null;
        inlineStyle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceOptionsThree';
      }
    | {
        id: string | null;
        title: string;
        subtitle: string;
        description: string;
        backgroundImage: number | Media;
        buttonText: string;
        buttonLink: string;
        btn_variant?: ('fill' | 'outline') | null;
        className?: string | null;
        inlineStyle?: string | null;
        blockName?: string | null;
        blockType: 'heroFour';
      }
  )[];
  theme: number | Theme;
  mode: 'light' | 'dark';
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata".
 */
export interface Metadatum {
  id: number;
  meta: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
    faviconImage: number | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  className?: string | null;
  inlineStyle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  captchaType: 'none' | 'googlerecaptcha' | 'cloudflareturnstile';
  storageType: 'database' | 'database-and-excel';
  workflow?: string | null;
  form: number | Form;
  enableIntro?: boolean | null;
  btn_variant?: ('fill' | 'outline') | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  className?: string | null;
  inlineStyle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  name: string;
  pageTheme?: {
    textColor?: string | null;
    backgroundColor?: string | null;
    containerBackground?: string | null;
    headingColor?: string | null;
    googleFontUrl?: string | null;
    bodyFont?: string | null;
    headingFont?: string | null;
  };
  pageDarkTheme?: {
    textColor?: string | null;
    backgroundColor?: string | null;
    containerBackground?: string | null;
    headingColor?: string | null;
    googleFontUrl?: string | null;
    bodyFont?: string | null;
    headingFont?: string | null;
  };
  navbar?: {
    textColor?: string | null;
    backgroundColor?: string | null;
    dark?: {
      textColor?: string | null;
      backgroundColor?: string | null;
    };
  };
  footer?: {
    textColor?: string | null;
    backgroundColor?: string | null;
    dark?: {
      textColor?: string | null;
      backgroundColor?: string | null;
    };
  };
  variants?: {
    fill?: {
      textColor?: string | null;
      backgroundColor?: string | null;
    };
    outline?: {
      textColor?: string | null;
      borderColor?: string | null;
      backgroundColor?: string | null;
    };
  };
  customThemes?:
    | {
        className: string;
        textColor?: string | null;
        backgroundColor?: string | null;
        descriptionColor?: string | null;
        mode?: ('light' | 'dark') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'metadata';
        value: number | Metadatum;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedAt?: T;
  restaurant?: T;
  path?: T;
  metadata?: T;
  layout?:
    | T
    | {
        navigation?:
          | T
          | {
              logo?:
                | T
                | {
                    image?: T;
                    alt?: T;
                  };
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    text?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        heroOne?:
          | T
          | {
              id?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              buttonText?: T;
              buttonLink?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        heroTwo?:
          | T
          | {
              id?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              btn_variant?: T;
              image?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        singleLocation?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    category?: T;
                    id?: T;
                  };
              menu?:
                | T
                | {
                    category?: T;
                    items?:
                      | T
                      | {
                          dish?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              buttonText?: T;
              btn_style?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        multipleLocations?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    address?: T;
                    hours?: T;
                    image?: T;
                    id?: T;
                  };
              rewardsTitle?: T;
              rewardsDescription?: T;
              buttonText?: T;
              btn_style?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              id?: T;
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    altText?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        franchise?:
          | T
          | {
              id?: T;
              title?: T;
              image?: T;
              franchiseSteps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              investmentDetails?:
                | T
                | {
                    title?: T;
                    amount?: T;
                    id?: T;
                  };
              buttonText?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        menu?:
          | T
          | {
              id?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    category?: T;
                    specialTag?: T;
                    image?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              fields?:
                | T
                | {
                    label?: T;
                    name?: T;
                    type?: T;
                    required?: T;
                    id?: T;
                  };
              buttonText?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              image?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        footer?:
          | T
          | {
              id?: T;
              logo?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              copyright?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        restaurant?:
          | T
          | {
              id?: T;
              title?: T;
              restaurants?:
                | T
                | {
                    title?: T;
                    cuisine?: T;
                    description?: T;
                    image?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    btn_style?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              id?: T;
              title?: T;
              locations?:
                | T
                | {
                    image?: T;
                    name?: T;
                    address?: T;
                    buttonText?: T;
                    orderNowUrl?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        location_scroll?:
          | T
          | {
              id?: T;
              title?: T;
              locations?:
                | T
                | {
                    image?: T;
                    name?: T;
                    address?: T;
                    orderNowUrl?: T;
                    id?: T;
                  };
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        foodcourt?:
          | T
          | {
              id?: T;
              title?: T;
              categories?:
                | T
                | {
                    categoryName?: T;
                    restaurants?:
                      | T
                      | {
                          title?: T;
                          cuisine?: T;
                          description?: T;
                          image?: T;
                          buttonText?: T;
                          buttonLink?: T;
                          variant?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        chef_details?:
          | T
          | {
              id?: T;
              title?: T;
              chefs?:
                | T
                | {
                    image?: T;
                    name?: T;
                    expertise?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        about1?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              id?: T;
              title?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    designation?: T;
                    testimonialText?: T;
                    image?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        chef_sroll_details?:
          | T
          | {
              id?: T;
              title?: T;
              chefs?:
                | T
                | {
                    image?: T;
                    name?: T;
                    expertise?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        contact_us?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              email?: T;
              phoneNumber?: T;
              address?: T;
              openHours?:
                | T
                | {
                    day?: T;
                    hours?: T;
                    id?: T;
                  };
              image?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        abouttwo?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              image?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        menu1?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    category?: T;
                    description?: T;
                    image?: T;
                    price?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        contactus?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              email?: T;
              phoneNumber?: T;
              address?: T;
              openHours?:
                | T
                | {
                    day?: T;
                    hours?: T;
                    id?: T;
                  };
              image?: T;
              fields?:
                | T
                | {
                    label?: T;
                    name?: T;
                    type?: T;
                    required?: T;
                    id?: T;
                  };
              buttonText?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        navigationDropDown?:
          | T
          | {
              theme?: T;
              logo?:
                | T
                | {
                    image?: T;
                    alt?: T;
                  };
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    text?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              menu?:
                | T
                | {
                    text?: T;
                    url?: T;
                    submenu?:
                      | T
                      | {
                          text?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        heroThree?:
          | T
          | {
              id?: T;
              imageShape?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              btn_variant?: T;
              image?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
        contact_two?:
          | T
          | {
              captchaType?: T;
              storageType?: T;
              workflow?: T;
              title?: T;
              description?: T;
              form?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        menutwo?:
          | T
          | {
              title?: T;
              categories?:
                | T
                | {
                    categoryName?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          rating?: T;
                          price?: T;
                          image?: T;
                          buttonText?: T;
                          buttonLink?: T;
                          btn_variant?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        menudisplay?:
          | T
          | {
              menu?:
                | T
                | {
                    title?: T;
                    image?: T;
                    buttonLink?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        menuthree?:
          | T
          | {
              title?: T;
              menu?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          rating?: T;
                          price?: T;
                          image?: T;
                          buttonText?: T;
                          buttonLink?: T;
                          btn_variant?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              video?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        videoone?:
          | T
          | {
              title?: T;
              videoId?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        videotwo?:
          | T
          | {
              title?: T;
              videos?:
                | T
                | {
                    videoId?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        videothree?:
          | T
          | {
              title?: T;
              videoId?: T;
              description?: T;
              image?: T;
              mediaPosition?: T;
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        galleryone?:
          | T
          | {
              layoutType?: T;
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    altText?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        testimonialtwo?:
          | T
          | {
              title?: T;
              image?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    designation?: T;
                    testimonialText?: T;
                    Personimage?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        MainPage?:
          | T
          | {
              title?: T;
              pages?:
                | T
                | {
                    image?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          page?: T;
                          text?: T;
                        };
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        menufour?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    iconName?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    backgroundColor?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        serviceOptions?:
          | T
          | {
              heading?: T;
              options?:
                | T
                | {
                    name?: T;
                    icon?: T;
                    link?: T;
                    btn_variant?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        foodcourtone?:
          | T
          | {
              title?: T;
              restaurants?:
                | T
                | {
                    title?: T;
                    cuisine?: T;
                    description?: T;
                    image?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    variant?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        serviceOptionsTwo?:
          | T
          | {
              heading?: T;
              options?:
                | T
                | {
                    name?: T;
                    icon?: T;
                    link?: T;
                    badge?: T;
                    subtitle?: T;
                    actionText?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        'menu-categories'?:
          | T
          | {
              heading?: T;
              description?: T;
              menuCategories?:
                | T
                | {
                    name?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        navigationTwo?:
          | T
          | {
              logo?:
                | T
                | {
                    image?: T;
                    alt?: T;
                  };
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    text?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        navigationThree?:
          | T
          | {
              colorScheme?: T;
              mode?: T;
              logo?:
                | T
                | {
                    image?: T;
                    alt?: T;
                  };
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        instagram?:
          | T
          | {
              title?: T;
              videos?:
                | T
                | {
                    platform?: T;
                    videoUrl?: T;
                    thumbnail?: T;
                    reelTitle?: T;
                    views?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        heroVideo?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              buttonText?: T;
              videos?:
                | T
                | {
                    uploadedVideo?: T;
                    videoUrl?: T;
                    thumbnail?: T;
                    id?: T;
                  };
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        serviceOptionsThree?:
          | T
          | {
              heading?: T;
              options?:
                | T
                | {
                    icon?: T;
                    name?: T;
                    link?: T;
                    description?: T;
                    buttonText?: T;
                    id?: T;
                  };
              className?: T;
              inlineStyle?: T;
              id?: T;
              blockName?: T;
            };
        heroFour?:
          | T
          | {
              id?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              buttonText?: T;
              buttonLink?: T;
              btn_variant?: T;
              className?: T;
              inlineStyle?: T;
              blockName?: T;
            };
      };
  theme?: T;
  mode?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  className?: T;
  inlineStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  captchaType?: T;
  storageType?: T;
  workflow?: T;
  form?: T;
  enableIntro?: T;
  btn_variant?: T;
  introContent?: T;
  className?: T;
  inlineStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata_select".
 */
export interface MetadataSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        faviconImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  pageTheme?:
    | T
    | {
        textColor?: T;
        backgroundColor?: T;
        containerBackground?: T;
        headingColor?: T;
        googleFontUrl?: T;
        bodyFont?: T;
        headingFont?: T;
      };
  pageDarkTheme?:
    | T
    | {
        textColor?: T;
        backgroundColor?: T;
        containerBackground?: T;
        headingColor?: T;
        googleFontUrl?: T;
        bodyFont?: T;
        headingFont?: T;
      };
  navbar?:
    | T
    | {
        textColor?: T;
        backgroundColor?: T;
        dark?:
          | T
          | {
              textColor?: T;
              backgroundColor?: T;
            };
      };
  footer?:
    | T
    | {
        textColor?: T;
        backgroundColor?: T;
        dark?:
          | T
          | {
              textColor?: T;
              backgroundColor?: T;
            };
      };
  variants?:
    | T
    | {
        fill?:
          | T
          | {
              textColor?: T;
              backgroundColor?: T;
            };
        outline?:
          | T
          | {
              textColor?: T;
              borderColor?: T;
              backgroundColor?: T;
            };
      };
  customThemes?:
    | T
    | {
        className?: T;
        textColor?: T;
        backgroundColor?: T;
        descriptionColor?: T;
        mode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}